### ISSUE TITLE
Issue with IBM Wazi deploy installation

### ISSUE THREAD

**Issue by ratnamGT** [IBM/wazi-devspaces-images#1]
I am trying to set up and configure IBM Wazi deploy in Mainframe . I configured and created the python envs,ZOAU and wazi environment.I am getting below installation error when I am trying to install and configure IBM Wazi deploy with the following command after tar file extraction .We are not able to run any wazi deploy commands due to this error.

pip3 install wazideploy-3.0.0-py3.11-none-any.whl
![image](https://github.com/user-attachments/assets/aaefa0f0-d80b-43c7-b044-93941488e5cd)
![image](https://github.com/user-attachments/assets/b157b242-b4ca-4069-ba1c-80df8e7be6cb)
We are using Python 3.11.2, ZOAU version 1.2.3,IBM Wazi deploy version-3.0.0 .Could you please help us to resolve the issue?

**Comment by ArvinB** [comment]
@ratnamGT I recommend moving this to [here](https://github.com/IBM/dbb/discussions/264#discussioncomment-10073291)

Closing this out.
